---
- name: Copy the loki systemd service file
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0644
  notify: restart loki

- name: Copy the loki configuration
  template:
    src: loki.yaml.j2
    dest: "{{ loki_config_dir }}/loki.yaml"
    owner: root
    group: "{{ loki_system_group }}"
    mode: 0644
  notify: restart loki
