---
- name: Create the loki group
  group:
    name: "{{ loki_system_group }}"
    state: present
    system: true

- name: Create the loki user
  user:
    name: "{{ loki_system_user }}"
    groups: "{{ loki_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: create loki configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ loki_system_group }}"
    mode: 0770
  with_items:
    - "{{ loki_config_dir }}"

- name: download loki binary to local folder
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/{{ loki_release }}"
    dest: "/tmp/{{ loki_release }}"
    checksum: "sha256:{{ loki_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost

- name: propagate loki binaries to host
  unarchive:
    src: "/tmp/{{ loki_release }}"
    dest: "/tmp"

- name: move binary to /usr/local/bin
  copy:
    src: "/tmp/{{ loki_target }}"
    dest: "/usr/local/bin/loki"
    mode: 0755
    owner: root
    group: loki
  notify:
    - restart loki
