---
- name: Create the loki group
  group:
    name: "{{ loki_system_group }}"
    state: present
    system: true

- name: Create the loki user
  user:
    name: "{{ loki_system_user }}"
    groups: "{{ loki_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: create loki configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: loki
    mode: 0770
  with_items:
    - "{{ loki_config_dir }}"

- name: download loki binary to local folder
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki_linux_{{ go_arch }}.gz"
    dest: "/tmp/loki_linux_{{ go_arch }}.gz"
    checksum: "sha256:{{ loki_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  deletgate_to: localhost

- name: unpack loki binaries
  command: "gunzip /tmp/loki_linux_{{ go_arch }}.gz"
  args:
    creates: "/tmp/loki_linux_{{ go_arch }}"
  deletgate_to: localhost

- name: propagate loki binary
  copy:
    src: "/tmp/loki_linux_{{ go_arch }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - loki
  notify:
    - restart loki
