---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - loki_install
    - loki_configure
    - loki_run

- import_tasks: preflight.yml
  tags:
    - loki_install
    - loki_configure
    - loki_run

- import_tasks: install.yml
  become: true
  tags:
    - loki_install

- import_tasks: configure.yml
  become: true
  tags:
    - loki_configure

- name: Ensure loki is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: loki
    enabled: true
  tags:
    - loki_run
